### ISSUE TITLE
Query string parser

### ISSUE THREAD

**Issue by etaque** [etaque/elm-route-parser#1]
Wondering what would be best as output, to manage multi-valued params (aka lists): `Dict String (List String)` or `List (String, String)`.

Cf https://github.com/NoRedInk/take-home/pull/10
ping @eeue56 @gyzerok

**Comment by eeue56** [comment]
Can you give two different examples? I would prefer a dict, and that's what I did for my implementation. What are the use cases of a list here instead?

**Comment by etaque** [comment]
I can't see any usage for a list, case closed I guess. Thanks :)
I'll provide a raw access to the dict, and think about a nice way to extract typed values, as for path.

**Comment by eeue56** [comment]
Can you add an example of it or can you figure it out @gyzerok?

**Comment by etaque** [comment]
There are a few in the tests:
https://github.com/etaque/elm-route-parser/blob/master/test/Tests.elm#L68-L76

**Comment by gyzerok** [comment]
@etaque thanks! It would definitely help :+1:

**Comment by etaque** [comment]
@gyzerok I added something in the readme:
https://github.com/etaque/elm-route-parser#query-string

For the moment it's just a helper, it's not part of the routing strategy because I'm still undecided about the best way to handle it. But don't hesitate to ping me if you still need help on take-home.

**Comment by claudio-dalicandro** [comment]
Hi! I understand how the parse work, but I can't figure out how to use it if I can't match a route that contains a querystring... Should I build a customParam with this helper?
